"""Dominion Agent OS — Python package root."""
from __future__ import annotations

from dominion_agent.api import (
    AgentStore,
    ClaimResult,
    ComplexityMetrics,
    ComplexityReport,
    ConflictItem,
    ConflictReport,
    FileLock,
    ImpactReport,
    LockResult,
    PromptCompilation,
    ReviewFinding,
    ReviewReport,
    SafetyResult,
    Session,
    Task,
    TASK_TRANSITIONS,
    VALID_LOCK_MODES,
    VALID_REVIEW_VERDICTS,
    VALID_ROLES,
    VALID_SESSION_STATUSES,
    VALID_TASK_KINDS,
    VALID_TASK_STATUSES,
    abandon_session,
    acquire_lock,
    all_packages_report,
    analyze_impact,
    check_conflicts,
    claim_task,
    compile_prompt,
    complexity_report,
    create_task,
    end_session,
    get_session,
    get_task,
    heartbeat,
    list_claims,
    list_locks,
    list_sessions,
    list_tasks,
    record_touch,
    refresh_architecture,
    release_lock,
    release_task,
    run_adversarial_review,
    show_architecture,
    stale_locks,
    start_session,
    sync_ragd,
    update_task_evidence,
    update_task_status,
    COMPLEXITY_BUDGETS,
)

__version__ = "1.0.0"
